### ISSUE TITLE
Slow consumer with large backlog of records causes "No more than 1024 pending puts"

### ISSUE THREAD

**Issue by scott-abernethy** [pyr/kinsky#5]
When I start an async consumer on a topic with a large backlog of records, and the consumer is slow, I eventually get:

`Exception in thread "async-dispatch-14" java.lang.AssertionError: Assert failed: No more than 1024 pending puts are allowed on a single channel. Consider using a windowed buffer.
(< (.size puts) impl/MAX-QUEUE-SIZE)
    at clojure.core.async.impl.channels.ManyToManyChannel.put_BANG_(channels.clj:152)
    at clojure.core.async$put_BANG_.invokeStatic(async.clj:159)
    at clojure.core.async$put_BANG_.invoke(async.clj:152)
    at kinsky.async$consumer$fn__12525$state_machine__8801__auto____12526$fn__12529.invoke(async.clj:159)
`

This is when the async consumer adds new payload on to the `recs` channel it uses `put!`.

Thanks.

**Comment by scott-abernethy** [comment]
FYI that was with kinsky 0.1.12

**Comment by pyr** [comment]
Now fixed in master.
